services:
  # 1. Эмулятор AWS (LocalStack)
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  # 2. База данных (MongoDB)
  mongodb:
    container_name: mongodb_main
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Админка для базы (Mongo Express)
  mongo-express:
    container_name: mongo_express_main
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
volumes:
  mongo_data:
                  